version: '2'
networks:
    s1c:
      external: true
    s1u:
      external: true
    rfemu:
      ipam:
        driver: default
        config:
        - subnet: "192.168.51.0/24" 
services:
  enb:
    build: ./
    container_name: enbzmq
    cap_add:
      - SYS_NICE
    networks:
      s1c:
        ipv4_address: 10.15.16.9
      s1u: 
        ipv4_address: 10.15.17.9
      rfemu:
        ipv4_address: 192.168.51.100
    volumes:
      - ./run_enb.sh:/root/run_enb.sh
      - ./config:/config
     
    entrypoint:
      - "/bin/sh" 
      - "/root/run_enb.sh"

  ue:
    container_name: uezmq
    build: ./
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    networks:
      rfemu:
        ipv4_address: 192.168.51.101
    devices:
      - /dev/net/tun
    depends_on:
      - enb
    volumes:
      - ./run_ue.sh:/root/run_ue.sh
      - ./config:/config
    entrypoint:
      - /bin/sh
      - /root/run_ue.sh